objects:
  machine: [C-BS-I, C-DS-I, C-CS1-I, C-CS2-I, C-RS1-I, C-RS2-I]
  robot: R-1
  team-color: CYAN

init:
  free-location: [START, C-BS-I, C-DS-I, C-CS1-I, C-CS2-I, C-RS1-I, C-RS2-I]
  robot-waiting: [R-1]

goal:
  visited: [C-BS-I, C-DS-I, C-CS1-I, C-CS2-I, C-RS1-I, C-RS2-I]
