# This contains just the modifications to the base configuration
# required to operate with three robots.
# Note that the modifications are not additive but the values
# overwrite and replace the values in the base configuration.

objects:
  robot: [R-1, R-2, R-3]

init:
  robot-waiting: [R-1, R-2, R-3]
